package com.example.todo;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

public class HomeServlet extends HttpServlet {
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) 
            throws ServletException, IOException {
        response.setContentType("text/html; charset=UTF-8");
        PrintWriter out = response.getWriter();
        
        out.println("<!DOCTYPE html>");
        out.println("<html lang=\"en\">");
        out.println("<head>");
        out.println("    <meta charset=\"UTF-8\">");
        out.println("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        out.println("    <title>Modern TODO List - Task Manager</title>");
        out.println("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">");
        out.println("    <style>");
        out.println("        * {");
        out.println("            margin: 0;");
        out.println("            padding: 0;");
        out.println("            box-sizing: border-box;");
        out.println("        }");
        out.println("");
        out.println("        :root {");
        out.println("            --primary: #667eea;");
        out.println("            --secondary: #764ba2;");
        out.println("            --accent: #f093fb;");
        out.println("            --dark: #1a202c;");
        out.println("            --light: #f7fafc;");
        out.println("            --white: #ffffff;");
        out.println("            --text: #2d3748;");
        out.println("            --border: #e2e8f0;");
        out.println("            --success: #48bb78;");
        out.println("            --danger: #f56565;");
        out.println("        }");
        out.println("");
        out.println("        html {");
        out.println("            scroll-behavior: smooth;");
        out.println("        }");
        out.println("");
        out.println("        body {");
        out.println("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;");
        out.println("            color: var(--text);");
        out.println("            line-height: 1.6;");
        out.println("            background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%);");
        out.println("            min-height: 100vh;");
        out.println("            padding: 2rem;");
        out.println("        }");
        out.println("");
        out.println("        .container {");
        out.println("            max-width: 900px;");
        out.println("            margin: 0 auto;");
        out.println("        }");
        out.println("");
        out.println("        .header {");
        out.println("            text-align: center;");
        out.println("            color: var(--white);");
        out.println("            margin-bottom: 3rem;");
        out.println("            animation: slideDown 0.6s ease-out;");
        out.println("        }");
        out.println("");
        out.println("        @keyframes slideDown {");
        out.println("            from {");
        out.println("                opacity: 0;");
        out.println("                transform: translateY(-30px);");
        out.println("            }");
        out.println("            to {");
        out.println("                opacity: 1;");
        out.println("                transform: translateY(0);");
        out.println("            }");
        out.println("        }");
        out.println("");
        out.println("        .header h1 {");
        out.println("            font-size: 3rem;");
        out.println("            font-weight: 800;");
        out.println("            margin-bottom: 0.5rem;");
        out.println("            text-shadow: 0 2px 10px rgba(0, 0, 0, 0.2);");
        out.println("        }");
        out.println("");
        out.println("        .header p {");
        out.println("            font-size: 1.1rem;");
        out.println("            opacity: 0.95;");
        out.println("        }");
        out.println("");
        out.println("        .todo-card {");
        out.println("            background: var(--white);");
        out.println("            border-radius: 20px;");
        out.println("            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);");
        out.println("            overflow: hidden;");
        out.println("            animation: slideUp 0.8s ease-out;");
        out.println("        }");
        out.println("");
        out.println("        @keyframes slideUp {");
        out.println("            from {");
        out.println("                opacity: 0;");
        out.println("                transform: translateY(30px);");
        out.println("            }");
        out.println("            to {");
        out.println("                opacity: 1;");
        out.println("                transform: translateY(0);");
        out.println("            }");
        out.println("        }");
        out.println("");
        out.println("        .input-section {");
        out.println("            background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%);");
        out.println("            padding: 2.5rem;");
        out.println("            color: var(--white);");
        out.println("        }");
        out.println("");
        out.println("        .input-group {");
        out.println("            display: flex;");
        out.println("            gap: 1rem;");
        out.println("            margin-bottom: 1.5rem;");
        out.println("        }");
        out.println("");
        out.println("        .input-group input {");
        out.println("            flex: 1;");
        out.println("            padding: 1rem;");
        out.println("            border: none;");
        out.println("            border-radius: 12px;");
        out.println("            font-size: 1rem;");
        out.println("            font-family: inherit;");
        out.println("            transition: all 0.3s ease;");
        out.println("        }");
        out.println("");
        out.println("        .input-group input:focus {");
        out.println("            outline: none;");
        out.println("            box-shadow: 0 0 0 3px rgba(255, 255, 255, 0.3);");
        out.println("            transform: scale(1.02);");
        out.println("        }");
        out.println("");
        out.println("        .input-group input::placeholder {");
        out.println("            color: rgba(255, 255, 255, 0.7);");
        out.println("        }");
        out.println("");
        out.println("        .btn-add {");
        out.println("            background: var(--white);");
        out.println("            color: var(--primary);");
        out.println("            border: none;");
        out.println("            padding: 1rem 2rem;");
        out.println("            border-radius: 12px;");
        out.println("            font-weight: 700;");
        out.println("            font-size: 1rem;");
        out.println("            cursor: pointer;");
        out.println("            transition: all 0.3s ease;");
        out.println("            display: flex;");
        out.println("            align-items: center;");
        out.println("            gap: 0.5rem;");
        out.println("            white-space: nowrap;");
        out.println("        }");
        out.println("");
        out.println("        .btn-add:hover {");
        out.println("            transform: translateY(-3px);");
        out.println("            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.2);");
        out.println("        }");
        out.println("");
        out.println("        .stats {");
        out.println("            display: flex;");
        out.println("            gap: 1rem;");
        out.println("            margin-top: 1rem;");
        out.println("            font-size: 0.9rem;");
        out.println("            opacity: 0.9;");
        out.println("        }");
        out.println("");
        out.println("        .stat {");
        out.println("            display: flex;");
        out.println("            align-items: center;");
        out.println("            gap: 0.5rem;");
        out.println("        }");
        out.println("");
        out.println("        .tasks-section {");
        out.println("            padding: 2rem;");
        out.println("            min-height: 300px;");
        out.println("        }");
        out.println("");
        out.println("        .tasks-list {");
        out.println("            display: flex;");
        out.println("            flex-direction: column;");
        out.println("            gap: 0.8rem;");
        out.println("        }");
        out.println("");
        out.println("        .task-item {");
        out.println("            display: flex;");
        out.println("            align-items: center;");
        out.println("            gap: 1rem;");
        out.println("            padding: 1.2rem;");
        out.println("            background: var(--light);");
        out.println("            border-radius: 12px;");
        out.println("            border-left: 4px solid var(--primary);");
        out.println("            transition: all 0.3s ease;");
        out.println("            animation: fadeIn 0.3s ease-out;");
        out.println("        }");
        out.println("");
        out.println("        @keyframes fadeIn {");
        out.println("            from {");
        out.println("                opacity: 0;");
        out.println("                transform: translateX(-20px);");
        out.println("            }");
        out.println("            to {");
        out.println("                opacity: 1;");
        out.println("                transform: translateX(0);");
        out.println("            }");
        out.println("        }");
        out.println("");
        out.println("        .task-item:hover {");
        out.println("            background: var(--white);");
        out.println("            box-shadow: 0 5px 20px rgba(0, 0, 0, 0.08);");
        out.println("            transform: translateX(5px);");
        out.println("            border-left-color: var(--accent);");
        out.println("        }");
        out.println("");
        out.println("        .task-item.completed {");
        out.println("            border-left-color: var(--success);");
        out.println("            opacity: 0.7;");
        out.println("        }");
        out.println("");
        out.println("        .task-item.completed .task-text {");
        out.println("            text-decoration: line-through;");
        out.println("            color: #a0aec0;");
        out.println("        }");
        out.println("");
        out.println("        .task-checkbox {");
        out.println("            width: 24px;");
        out.println("            height: 24px;");
        out.println("            cursor: pointer;");
        out.println("            appearance: none;");
        out.println("            background: var(--white);");
        out.println("            border: 2px solid var(--primary);");
        out.println("            border-radius: 6px;");
        out.println("            transition: all 0.3s ease;");
        out.println("            flex-shrink: 0;");
        out.println("            display: flex;");
        out.println("            align-items: center;");
        out.println("            justify-content: center;");
        out.println("        }");
        out.println("");
        out.println("        .task-checkbox:hover {");
        out.println("            border-color: var(--accent);");
        out.println("            background: rgba(240, 147, 251, 0.1);");
        out.println("        }");
        out.println("");
        out.println("        .task-checkbox:checked {");
        out.println("            background: linear-gradient(135deg, var(--success) 0%, var(--primary) 100%);");
        out.println("            border-color: var(--success);");
        out.println("        }");
        out.println("");
        out.println("        .task-content {");
        out.println("            flex: 1;");
        out.println("            display: flex;");
        out.println("            align-items: center;");
        out.println("            gap: 1rem;");
        out.println("        }");
        out.println("");
        out.println("        .task-text {");
        out.println("            font-size: 1rem;");
        out.println("            font-weight: 500;");
        out.println("            color: var(--text);");
        out.println("            transition: all 0.3s ease;");
        out.println("            word-break: break-word;");
        out.println("            max-width: 500px;");
        out.println("        }");
        out.println("");
        out.println("        .task-text-input {");
        out.println("            width: 100%;");
        out.println("            padding: 0.5rem;");
        out.println("            border: 2px solid var(--primary);");
        out.println("            border-radius: 8px;");
        out.println("            font-size: 1rem;");
        out.println("            font-family: inherit;");
        out.println("            font-weight: 500;");
        out.println("            color: var(--text);");
        out.println("            transition: all 0.3s ease;");
        out.println("        }");
        out.println("");
        out.println("        .task-text-input:focus {");
        out.println("            outline: none;");
        out.println("            border-color: var(--accent);");
        out.println("            box-shadow: 0 0 0 3px rgba(240, 147, 251, 0.2);");
        out.println("        }");
        out.println("");
        out.println("        .task-actions {");
        out.println("            display: flex;");
        out.println("            gap: 0.5rem;");
        out.println("            flex-shrink: 0;");
        out.println("        }");
        out.println("");
        out.println("        .task-btn {");
        out.println("            width: 36px;");
        out.println("            height: 36px;");
        out.println("            border: none;");
        out.println("            border-radius: 8px;");
        out.println("            cursor: pointer;");
        out.println("            transition: all 0.3s ease;");
        out.println("            display: flex;");
        out.println("            align-items: center;");
        out.println("            justify-content: center;");
        out.println("            font-size: 0.9rem;");
        out.println("            background: transparent;");
        out.println("        }");
        out.println("");
        out.println("        .task-btn:hover {");
        out.println("            transform: scale(1.1);");
        out.println("        }");
        out.println("");
        out.println("        .btn-edit {");
        out.println("            color: var(--primary);");
        out.println("            background: rgba(102, 126, 234, 0.1);");
        out.println("        }");
        out.println("");
        out.println("        .btn-delete {");
        out.println("            color: var(--danger);");
        out.println("            background: rgba(245, 101, 101, 0.1);");
        out.println("        }");
        out.println("");
        out.println("        .btn-save {");
        out.println("            color: var(--success);");
        out.println("            background: rgba(72, 187, 120, 0.1);");
        out.println("        }");
        out.println("");
        out.println("        .btn-cancel {");
        out.println("            color: var(--text);");
        out.println("            background: rgba(45, 55, 72, 0.1);");
        out.println("        }");
        out.println("");
        out.println("        .empty-state {");
        out.println("            text-align: center;");
        out.println("            padding: 3rem 2rem;");
        out.println("            color: #a0aec0;");
        out.println("        }");
        out.println("");
        out.println("        .filter-section {");
        out.println("            display: flex;");
        out.println("            gap: 0.5rem;");
        out.println("            margin-bottom: 1.5rem;");
        out.println("            justify-content: center;");
        out.println("            padding: 1.5rem;");
        out.println("            border-bottom: 1px solid var(--border);");
        out.println("        }");
        out.println("");
        out.println("        .filter-btn {");
        out.println("            padding: 0.5rem 1rem;");
        out.println("            border: 2px solid var(--border);");
        out.println("            background: var(--white);");
        out.println("            border-radius: 20px;");
        out.println("            cursor: pointer;");
        out.println("            transition: all 0.3s ease;");
        out.println("            font-weight: 600;");
        out.println("            font-size: 0.9rem;");
        out.println("        }");
        out.println("");
        out.println("        .filter-btn:hover,");
        out.println("        .filter-btn.active {");
        out.println("            background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%);");
        out.println("            color: var(--white);");
        out.println("            border-color: transparent;");
        out.println("        }");
        out.println("");
        out.println("        @media (max-width: 768px) {");
        out.println("            body { padding: 1rem; }");
        out.println("            .header h1 { font-size: 2rem; }");
        out.println("            .input-group { flex-direction: column; }");
        out.println("            .input-group input, .btn-add { width: 100%; }");
        out.println("        }");
        out.println("");
        out.println("        .loading { text-align: center; padding: 2rem; color: var(--primary); }");
        out.println("        .loading i { animation: spin 1s linear infinite; }");
        out.println("        @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }");
        out.println("    </style>");
        out.println("</head>");
        out.println("<body>");
        out.println("    <div class=\"container\">");
        out.println("        <div class=\"header\">");
        out.println("            <h1><i class=\"fas fa-tasks\"></i> TODO Manager</h1>");
        out.println("            <p>Stay organized and manage your tasks efficiently</p>");
        out.println("        </div>");
        out.println("");
        out.println("        <div class=\"todo-card\">");
        out.println("            <div class=\"input-section\">");
        out.println("                <div class=\"input-group\">");
        out.println("                    <input type=\"text\" id=\"taskInput\" placeholder=\"Add a new task...\" autocomplete=\"off\">");
        out.println("                    <button class=\"btn-add\" onclick=\"addTask()\">");
        out.println("                        <i class=\"fas fa-plus\"></i> Add Task");
        out.println("                    </button>");
        out.println("                </div>");
        out.println("                <div class=\"stats\">");
        out.println("                    <div class=\"stat\"><i class=\"fas fa-list-check\"></i> <span id=\"totalTasks\">0</span> Total</div>");
        out.println("                    <div class=\"stat\"><i class=\"fas fa-check-circle\"></i> <span id=\"completedTasks\">0</span> Completed</div>");
        out.println("                    <div class=\"stat\"><i class=\"fas fa-circle\"></i> <span id=\"pendingTasks\">0</span> Pending</div>");
        out.println("                </div>");
        out.println("            </div>");
        out.println("");
        out.println("            <div class=\"filter-section\">");
        out.println("                <button class=\"filter-btn active\" onclick=\"filterTasks(event, 'all')\">All</button>");
        out.println("                <button class=\"filter-btn\" onclick=\"filterTasks(event, 'active')\">Active</button>");
        out.println("                <button class=\"filter-btn\" onclick=\"filterTasks(event, 'completed')\">Completed</button>");
        out.println("            </div>");
        out.println("");
        out.println("            <div class=\"tasks-section\">");
        out.println("                <div id=\"tasksList\" class=\"tasks-list\">");
        out.println("                    <div class=\"loading\"><i class=\"fas fa-spinner\"></i> Loading tasks...</div>");
        out.println("                </div>");
        out.println("            </div>");
        out.println("");
        out.println("            <div id=\"emptyState\" class=\"empty-state\" style=\"display: none;\">");
        out.println("                <i class=\"fas fa-inbox\"></i><p>No tasks yet. Create one to get started!</p>");
        out.println("            </div>");
        out.println("        </div>");
        out.println("    </div>");
        out.println("");
        out.println("    <script>");
        out.println("        let allTasks = [];");
        out.println("        let currentFilter = 'all';");
        out.println("        let editingId = null;");
        out.println("");
        out.println("        document.addEventListener('DOMContentLoaded', function() {");
        out.println("            loadTasks();");
        out.println("            document.getElementById('taskInput').addEventListener('keypress', function(e) {");
        out.println("                if (e.key === 'Enter') { addTask(); }");
        out.println("            });");
        out.println("        });");
        out.println("");
        out.println("        function loadTasks() {");
        out.println("            fetch('/api/tasks?action=list')");
        out.println("                .then(r => r.json())");
        out.println("                .then(tasks => {");
        out.println("                    allTasks = tasks || [];");
        out.println("                    updateStats();");
        out.println("                    renderTasks();");
        out.println("                })");
        out.println("                .catch(e => {");
        out.println("                    console.error('Error:', e);");
        out.println("                    document.getElementById('tasksList').innerHTML = '<div class=\"empty-state\"><i class=\"fas fa-exclamation-circle\"></i><p>Error loading tasks.</p></div>';");
        out.println("                });");
        out.println("        }");
        out.println("");
        out.println("        function addTask() {");
        out.println("            const input = document.getElementById('taskInput');");
        out.println("            const title = input.value.trim();");
        out.println("            if (title === '') { alert('Enter a task'); return; }");
        out.println("            const form = new URLSearchParams();");
        out.println("            form.append('action', 'add');");
        out.println("            form.append('title', title);");
        out.println("            fetch('/api/tasks', { method: 'POST', body: form })");
        out.println("                .then(r => r.json())");
        out.println("                .then(task => {");
        out.println("                    allTasks.unshift(task);");
        out.println("                    input.value = '';");
        out.println("                    updateStats();");
        out.println("                    renderTasks();");
        out.println("                })");
        out.println("                .catch(e => { console.error('Error:', e); alert('Error adding task'); });");
        out.println("        }");
        out.println("");
        out.println("        function toggleTask(id) {");
        out.println("            const form = new URLSearchParams();");
        out.println("            form.append('action', 'toggle');");
        out.println("            form.append('id', id);");
        out.println("            fetch('/api/tasks', { method: 'PUT', body: form })");
        out.println("                .then(r => r.json())");
        out.println("                .then(updated => {");
        out.println("                    const idx = allTasks.findIndex(t => t.id === id);");
        out.println("                    if (idx > -1) allTasks[idx] = updated;");
        out.println("                    updateStats();");
        out.println("                    renderTasks();");
        out.println("                });");
        out.println("        }");
        out.println("");
        out.println("        function deleteTask(id) {");
        out.println("            if (!confirm('Delete this task?')) return;");
        out.println("            fetch('/api/tasks?id=' + id, { method: 'DELETE' })");
        out.println("                .then(r => r.json())");
        out.println("                .then(() => {");
        out.println("                    allTasks = allTasks.filter(t => t.id !== id);");
        out.println("                    updateStats();");
        out.println("                    renderTasks();");
        out.println("                });");
        out.println("        }");
        out.println("");
        out.println("        function startEdit(id) { editingId = id; renderTasks(); }");
        out.println("        function cancelEdit() { editingId = null; renderTasks(); }");
        out.println("");
        out.println("        function saveEdit(id) {");
        out.println("            const input = document.querySelector(`#edit-input-${id}`);");
        out.println("            const title = input.value.trim();");
        out.println("            if (title === '') { alert('Title required'); return; }");
        out.println("            const task = allTasks.find(t => t.id === id);");
        out.println("            const form = new URLSearchParams();");
        out.println("            form.append('action', 'update');");
        out.println("            form.append('id', id);");
        out.println("            form.append('title', title);");
        out.println("            form.append('completed', task.completed);");
        out.println("            fetch('/api/tasks', { method: 'PUT', body: form })");
        out.println("                .then(r => r.json())");
        out.println("                .then(updated => {");
        out.println("                    const idx = allTasks.findIndex(t => t.id === id);");
        out.println("                    if (idx > -1) allTasks[idx] = updated;");
        out.println("                    editingId = null;");
        out.println("                    renderTasks();");
        out.println("                });");
        out.println("        }");
        out.println("");
        out.println("        function filterTasks(e, filter) {");
        out.println("            currentFilter = filter;");
        out.println("            document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));");
        out.println("            e.target.classList.add('active');");
        out.println("            renderTasks();");
        out.println("        }");
        out.println("");
        out.println("        function updateStats() {");
        out.println("            const total = allTasks.length;");
        out.println("            const completed = allTasks.filter(t => t.completed).length;");
        out.println("            document.getElementById('totalTasks').textContent = total;");
        out.println("            document.getElementById('completedTasks').textContent = completed;");
        out.println("            document.getElementById('pendingTasks').textContent = total - completed;");
        out.println("        }");
        out.println("");
        out.println("        function renderTasks() {");
        out.println("            const list = document.getElementById('tasksList');");
        out.println("            const empty = document.getElementById('emptyState');");
        out.println("            let filtered = allTasks;");
        out.println("            if (currentFilter === 'active') filtered = allTasks.filter(t => !t.completed);");
        out.println("            else if (currentFilter === 'completed') filtered = allTasks.filter(t => t.completed);");
        out.println("            if (filtered.length === 0) {");
        out.println("                list.style.display = 'none';");
        out.println("                empty.style.display = 'block';");
        out.println("                return;");
        out.println("            }");
        out.println("            list.style.display = 'flex';");
        out.println("            empty.style.display = 'none';");
        out.println("            list.innerHTML = filtered.map(t => `");
        out.println("                <div class=\"task-item ${t.completed ? 'completed' : ''}\"> ");
        out.println("                    <input type=\"checkbox\" class=\"task-checkbox\" ${t.completed ? 'checked' : ''} onchange=\"toggleTask(${t.id})\">");
        out.println("                    <div class=\"task-content\">");
        out.println("                        ${editingId === t.id ? `<input type='text' id='edit-input-${t.id}' class='task-text-input' value='${escapeHtml(t.title)}' autofocus>` : `<span class='task-text'>${escapeHtml(t.title)}</span>`}");
        out.println("                    </div>");
        out.println("                    <div class=\"task-actions\">");
        out.println("                        ${editingId === t.id ? ");
        out.println("                            `<button class='task-btn btn-save' onclick='saveEdit(${t.id})' title='Save'><i class='fas fa-check'></i></button>");
        out.println("                             <button class='task-btn btn-cancel' onclick='cancelEdit()' title='Cancel'><i class='fas fa-times'></i></button>` :");
        out.println("                            `<button class='task-btn btn-edit' onclick='startEdit(${t.id})' title='Edit'><i class='fas fa-pen'></i></button>");
        out.println("                             <button class='task-btn btn-delete' onclick='deleteTask(${t.id})' title='Delete'><i class='fas fa-trash'></i></button>`");
        out.println("                        }");
        out.println("                    </div>");
        out.println("                </div>");
        out.println("            `).join('');");
        out.println("        }");
        out.println("");
        out.println("        function escapeHtml(t) {");
        out.println("            const d = document.createElement('div');");
        out.println("            d.textContent = t;");
        out.println("            return d.innerHTML;");
        out.println("        }");
        out.println("    </script>");
        out.println("</body>");
        out.println("</html>");
    }
}
